server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: warehouse
  kafka:
#    bootstrap-servers: localhost:9092
#    bootstrap-servers: kafka:9092
    bootstrap-servers: host.docker.internal:29092


  datasource:
#    url: jdbc:postgresql://${DATASOURCE_URL:localhost}:5436/warehouse?searchPath=ms_warehouse
#    username: ${DATASOURCE_USERNAME:warehouse_usr}
#    password: ${DATASOURCE_PASSWORD:warehouse_pswd}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/database_ms_warehouse-changelog.xml
    default-schema: ms_warehouse
    drop-first: true  # Добавлено, чтобы сначала дропнуть все таблицы перед применением миграций

logging:
  level:
    org.springframework.boot.context.config: debug
    liquibase: debug
    org.springframework.security: debug

app:
  kafka:
    topic: cargo-topic