services:
  warehouse-db:
    image: postgres:15
    container_name: warehouse
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse_usr
      POSTGRES_PASSWORD: warehouse_pswd
    volumes:
      - warehouse_data:/var/lib/postgresql/data

volumes:
  warehouse_data:
